sudo: required

language: python
python:
 - "3.5"
 - "3.6"
 - "3.7"


install:
 - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH="$HOME/miniconda/bin:$PATH"
 - hash -r
 - conda config --set always_yes yes --set changeps1 no
 - conda update -q conda
 - conda info -a
 - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION pytest rpy2 pytest-cov pyyaml
 - source activate test-env
 - pip install .
 - conda install -c r devtools
 - cd rveg; Rscript -e "devtools::load_all()"; cd -;

script:
 - pytest -s
 - cd rveg; Rscript -e "devtools::test()"; cd -;

after_failure:
 - cat config.log

after_success:
 - echo "All tests passed!"