name: gee
channels:
  - conda-forge
  - defaults
dependencies:
  - argparse
  - requests
  - earthengine-api
  - numpy
  - matplotlib
  - dateparser
  - pip
  - matplotlib
  - pip:
  - Pillow=6.2.1
  - pytest
#  - geetools


